import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,NavLink,Navigate,Route,Routes,useNavigate,useParams} from 'react-router-dom';
import {AlertTriangle,ArrowRight,BookOpen,ChevronRight,CircleHelp,Code2,CreditCard,KeyRound,LayoutDashboard,Menu,Search,ShieldCheck,WalletCards,Webhook,X,Building2,LockKeyhole,CheckCircle2} from 'lucide-react';
import './styles.css';
import type {MerchantAccount,Payment} from './domain';
import {paymentSemantic} from './domain';
import {merchantApi,merchantApiBoundary,MerchantApiSecurityBoundaryError} from './merchant-api';
import {pilotCapabilities,pilotPresentation} from './pilot';

const navGroups=[
  {label:'OPERATIONS',items:[['/app/overview','Overview',LayoutDashboard],['/app/payments','Payment lookup',CreditCard],['/app/checkouts','Checkouts',WalletCards]]},
  {label:'DEVELOPERS',items:[['/app/developers','Integration',Code2],['/app/webhooks','Webhook endpoint',Webhook]]},
  {label:'ACCOUNT',items:[['/app/account','Merchant account',Building2]]},
];

function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'active'}){return <span className={`badge ${tone}`}>{children}</span>}
function VeroxBrand(){return <div className="brand"><img src="/verox-mark.svg" alt=""/><div><strong>VEROX</strong><small>MERCHANT</small></div></div>}
function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <section className="page-intro"><div><span className="eyebrow">{eyebrow??'MERCHANT PLATFORM'}</span><h1>{title}</h1><p>{description}</p></div>{action}</section>}
function OperationalNotice({title,detail,tone='info'}:{title:string;detail:string;tone?:'info'|'warning'}){return <div className={tone==='warning'?'contract-banner':'data-notice'}>{tone==='warning'?<AlertTriangle size={16}/>:<ShieldCheck size={16}/>}<div><strong>{title}</strong><span>{detail}</span></div></div>}
function SecurityBoundary(){return <OperationalNotice tone="warning" title="Secure Merchant API boundary required" detail="This dashboard is currently a browser-only Vite application. VEROX Merchant API keys are server secrets, so authenticated /v1/* calls remain intentionally blocked until a server-owned BFF/proxy boundary exists."/>}
function PilotContext(){return <div className="merchant-context"><span>PILOT PRESENTATION</span><strong>{pilotPresentation.brandName}</strong><small>{pilotPresentation.primaryContactName} · TEST pilot</small></div>}

function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){return <aside className={`sidebar ${open?'open':''}`}><div className="sidebar-head"><VeroxBrand/><button className="icon-btn mobile-close" onClick={onClose} aria-label="Close navigation"><X size={18}/></button></div><PilotContext/><nav>{navGroups.map(g=><div className="nav-group" key={g.label}><span>{g.label}</span>{g.items.map(([to,label,Icon])=><NavLink key={String(to)} to={String(to)} onClick={onClose} className={({isActive})=>isActive?'active':''}><Icon size={17}/>{label}</NavLink>)}</div>)}</nav><div className="sidebar-foot"><div className="truth"><ShieldCheck size={17}/><div><strong>VEROX Server</strong><small>Payment truth authority</small></div></div><a href="https://github.com/rightware-corporations/verox-system" target="_blank" rel="noreferrer"><BookOpen size={16}/>Repository</a><button disabled title="Support channel is not configured"><CircleHelp size={16}/>Support</button></div></aside>}
function Topbar({onMenu}:{onMenu:()=>void}){const nav=useNavigate();const[q,setQ]=React.useState('');return <header className="topbar"><button className="icon-btn menu-btn" onClick={onMenu} aria-label="Open navigation"><Menu size={18}/></button><form className="global-search" onSubmit={e=>{e.preventDefault();const id=q.trim();if(id)nav('/app/payments/'+encodeURIComponent(id))}}><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Open payment by pay_* ID" aria-label="Payment ID"/><kbd>↵</kbd></form><Badge tone="active">TEST PILOT</Badge><NavLink to="/app/account" className="avatar">MM</NavLink></header>}

function Overview(){return <div className="page-stack"><PageHeader eyebrow="MONEY MAKERS PILOT" title="Pilot operations" description="The merchant console is intentionally limited to backend contracts that actually exist. No transaction list, review queue, team model or channel-management API is fabricated."/><SecurityBoundary/><section className="kpi-grid"><article className="kpi"><span>Pilot presentation</span><strong>Money Makers</strong><small>Primary contact: Owen de Jesus</small></article><article className="kpi"><span>Backend identity</span><strong>GET /v1/account</strong><small>Available after secure credential boundary</small></article><article className="kpi"><span>Payment truth</span><strong>GET /v1/payments/{'{id}'}</strong><small className="success">Real merchant-scoped contract</small></article><article className="kpi"><span>Manual acceptance</span><strong>{pilotCapabilities.canUsePilotManualAcceptance?'Enabled':'Blocked'}</strong><small className="warning">Never authorized by display name</small></article></section><section className="overview-layout"><article className="panel"><div className="panel-head"><div><span className="eyebrow">REAL PILOT PATH</span><h2>What the current frontend can safely expose</h2></div></div><div className="security-list"><div><CheckCircle2 size={17}/><span>Payment detail is modeled against the real GET /v1/payments/{'{paymentId}'} contract.</span></div><div><CheckCircle2 size={17}/><span>Core status and effective_status remain separate, including MANUALLY_ACCEPTED provenance.</span></div><div><CheckCircle2 size={17}/><span>Hosted Checkout remains capability-based and never uses a Merchant API key.</span></div><div><LockKeyhole size={17}/><span>Merchant API operations remain blocked in-browser until a secure server-owned credential boundary exists.</span></div></div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">NOT FABRICATED</span><h2>Future modules</h2></div></div><div className="health-list">{['Payments collection / search API','Review queue API','Team / human user / RBAC','Payment-channel management','Webhook delivery history','Tenant administration'].map(label=><div className="health-row" key={label}><span className="status-dot"/><div><strong>{label}</strong><small>Not exposed by the audited Merchant API</small></div></div>)}</div></article></section></div>}

function PaymentLookup(){const nav=useNavigate();const[id,setId]=React.useState('');return <div className="page-stack"><PageHeader title="Payment lookup" description="VEROX currently exposes payment retrieval by public pay_* ID. There is no audited GET /v1/payments collection/search endpoint."/><SecurityBoundary/><article className="panel summary-card"><span>Payment public ID</span><div className="filterbar"><label><Search size={15}/><input value={id} onChange={e=>setId(e.target.value)} placeholder="pay_..."/></label><button onClick={()=>id.trim()&&nav('/app/payments/'+encodeURIComponent(id.trim()))} disabled={!id.trim()}>Open payment <ArrowRight size={14}/></button></div><p style={{marginTop:14,color:'var(--muted)',fontSize:11}}>The lookup route is real. Retrieval remains security-blocked until the Merchant API can be called through a server-owned credential boundary.</p></article></div>}

function PaymentStatusSummary({payment}:{payment:Payment}){const effective=paymentSemantic(payment.effectiveStatus);const core=paymentSemantic(payment.status);return <section className="detail-grid"><article className="panel summary-card"><span>Amount</span><strong>{payment.amount} {payment.currency}</strong><dl><div><dt>Payment</dt><dd><code>{payment.id}</code></dd></div><div><dt>Reference</dt><dd>{payment.externalReference}</dd></div><div><dt>Provider</dt><dd>{payment.provider??'—'}</dd></div><div><dt>Checkout</dt><dd><code>{payment.checkoutSessionId}</code></dd></div></dl></article><article className="panel summary-card"><span>Payment truth</span><dl><div><dt>Core status</dt><dd><Badge tone={core.tone}>{core.label}</Badge></dd></div><div><dt>Effective status</dt><dd><Badge tone={effective.tone}>{effective.label}</Badge></dd></div><div><dt>Confirmed at</dt><dd>{payment.confirmedAt??'—'}</dd></div><div><dt>Manual acceptance</dt><dd>{payment.manuallyAcceptedAt??'—'}</dd></div></dl>{payment.effectiveStatus==='MANUALLY_ACCEPTED'&&<OperationalNotice tone="warning" title="Accepted manually" detail="Automatic verification was not used for this effective result. The core payment status remains independently authoritative."/>}</article></section>}

function PaymentDetail(){const{id=''}=useParams();const[payment,setPayment]=React.useState<Payment|null>(null);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState<string|null>(null);React.useEffect(()=>{let active=true;setLoading(true);setError(null);merchantApi.getPayment(id).then(p=>{if(active)setPayment(p)}).catch(err=>{if(!active)return;setError(err instanceof MerchantApiSecurityBoundaryError?err.message:'Payment could not be loaded. No payment state has been inferred from this infrastructure error.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id]);return <div className="page-stack"><PageHeader eyebrow="PAYMENT TRUTH RECORD" title={id||'Payment'} description="Payment core status and effective status are always rendered as separate backend concepts."/>{loading&&<article className="panel"><div className="empty"><strong>Loading payment…</strong><p>No placeholder payment truth is shown before the server responds.</p></div></article>}{error&&<><SecurityBoundary/><article className="panel"><div className="empty"><LockKeyhole size={22}/><strong>Payment retrieval is not connected in this browser build</strong><p>{error}</p></div></article></>}{payment&&<PaymentStatusSummary payment={payment}/>}<article className="panel"><div className="panel-head"><div><span className="eyebrow">PILOT MANUAL ACCEPTANCE</span><h2>Controlled operational action</h2></div></div><div className="security-list"><div><ShieldCheck size={17}/><span>Eligible only for PENDING or REVIEW_REQUIRED and only when server-side pilot capability is enabled.</span></div><div><ShieldCheck size={17}/><span>MANUALLY_ACCEPTED never becomes automatic CONFIRMED in the UI.</span></div><div><LockKeyhole size={17}/><span>Interactive acceptance is intentionally unavailable until secure Merchant API handling exists.</span></div></div></article></div>}

function Checkouts(){return <div className="page-stack"><PageHeader title="Checkouts" description="The backend supports create and get-by-ID checkout contracts, but both require the Merchant Bearer credential and therefore cannot be called directly from this browser application."/><SecurityBoundary/><section className="detail-grid"><article className="panel summary-card"><span>POST /v1/checkout/sessions</span><h2>Create checkout session</h2><p style={{marginTop:10,color:'var(--muted)',fontSize:11,lineHeight:1.6}}>Requires amount, currency, external_reference, optional description, success_url, cancel_url and a stable Idempotency-Key per logical submit attempt.</p></article><article className="panel summary-card"><span>GET /v1/checkout/sessions/{'{checkoutSessionId}'}</span><h2>Retrieve checkout</h2><p style={{marginTop:10,color:'var(--muted)',fontSize:11,lineHeight:1.6}}>Uses the public cs_* ID and remains merchant-scoped. Checkout state is not payment truth.</p></article></section></div>}

function Integration(){return <div className="page-stack"><PageHeader title="Integration" description="Real backend capability map for the Money Makers / Owen de Jesus pilot. Tenant-ready boundaries are retained without creating tenant administration."/><section className="integration-layout"><article className="panel progress-card"><div className="progress-summary"><span className="eyebrow">CURRENT PILOT</span><strong>TEST</strong><p>Production-like pilot testing has been proven with TEST credentials. LIVE manual acceptance is not assumed.</p></div><div className="step-list">{[['GET /v1/account','Real contract'],['POST /v1/checkout/sessions','Real contract'],['GET /v1/checkout/sessions/{id}','Real contract'],['GET /v1/payments/{id}','Real contract'],['POST /v1/pilot/manual-acceptances/{paymentId}','Real pilot contract'],['PUT /v1/webhook-endpoint','Real contract'],['Secure dashboard BFF / proxy','Required frontend dependency']].map(([label,detail],i)=><div className={i<6?'done':''} key={label}><span>{i<6?<CheckCircle2 size={16}/>:<LockKeyhole size={16}/>}</span><strong>{label}</strong><small>{detail}</small></div>)}</div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">DEPLOYMENT</span><h2>Hosted Checkout origin</h2></div></div><div className="security-list"><div><AlertTriangle size={17}/><span>VEROX_CHECKOUT_BASE_URL must point to the real public Hosted Checkout origin before public deployment.</span></div><div><ShieldCheck size={17}/><span>Do not rewrite backend-generated checkout URLs in the client.</span></div></div></article></section></div>}

function WebhookEndpoint(){return <div className="page-stack"><PageHeader title="Webhook endpoint" description="The audited Merchant API supports endpoint configuration only. No merchant-facing delivery-history API is fabricated."/><SecurityBoundary/><article className="panel summary-card"><span>PUT /v1/webhook-endpoint</span><h2>Delivery destination</h2><p style={{marginTop:10,color:'var(--muted)',fontSize:11,lineHeight:1.6}}>Request body: <code>{'{'}</code> "url": "https://..." <code>{'}'}</code>. Configuration remains unavailable in this browser build until authenticated Merchant API traffic has a secure server-owned boundary.</p></article></div>}

function Account(){const[account,setAccount]=React.useState<MerchantAccount|null>(null);const[loading,setLoading]=React.useState(true);React.useEffect(()=>{merchantApi.getAccount().then(setAccount).catch(()=>setAccount(null)).finally(()=>setLoading(false))},[]);return <div className="page-stack"><PageHeader title="Merchant account" description="Backend merchant identity and pilot presentation metadata are intentionally kept separate."/><section className="detail-grid"><article className="panel account-card"><span className="eyebrow">PILOT PRESENTATION</span><h2>{pilotPresentation.brandName}</h2><dl><div><dt>Primary contact</dt><dd>{pilotPresentation.primaryContactName}</dd></div><div><dt>Purpose</dt><dd>Presentation/configuration only</dd></div><div><dt>Authorization</dt><dd>Never derived from these names</dd></div></dl></article><article className="panel account-card"><span className="eyebrow">BACKEND MERCHANT IDENTITY</span><h2>{loading?'Loading…':account?.merchantName??'Not connected'}</h2>{account?<dl><div><dt>Merchant ID</dt><dd><code>{account.merchantId}</code></dd></div><div><dt>Environment</dt><dd><Badge tone="active">{account.environment}</Badge></dd></div></dl>:<SecurityBoundary/>}</article></section></div>}

function AppShell(){const[open,setOpen]=React.useState(false);return <div className="app-shell"><Sidebar open={open} onClose={()=>setOpen(false)}/><div className="workspace"><Topbar onMenu={()=>setOpen(true)}/><main className="content"><Routes><Route path="/app/overview" element={<Overview/>}/><Route path="/app/payments" element={<PaymentLookup/>}/><Route path="/app/payments/:id" element={<PaymentDetail/>}/><Route path="/app/checkouts" element={<Checkouts/>}/><Route path="/app/developers" element={<Integration/>}/><Route path="/app/webhooks" element={<WebhookEndpoint/>}/><Route path="/app/account" element={<Account/>}/><Route path="/app" element={<Navigate to="/app/overview" replace/>}/><Route path="*" element={<Navigate to="/app/overview" replace/>}/></Routes></main></div>{open&&<button className="scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}</div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><AppShell/></BrowserRouter></React.StrictMode>);
