import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,NavLink,Navigate,Route,Routes,useNavigate,useParams} from 'react-router-dom';
import {
  AlertTriangle,ArrowLeft,ArrowRight,CheckCircle2,ChevronLeft,ChevronRight,CreditCard,
  LayoutDashboard,LogOut,Menu,RefreshCw,Search,ShieldCheck,WalletCards,X,Building2,PlugZap
} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import './styles.css';
import type {OperatorSession,Payment,PaymentChannel,PaymentCoreState,PaymentListItem,PaymentPage} from './domain';
import {canAcceptManually,paymentSemantic} from './domain';
import {platformApi,PlatformApiError,PlatformCsrfUnavailableError,PLATFORM_BACKEND_ORIGIN} from './platform-api';

type NavItem=readonly[to:string,label:string,icon:LucideIcon];
const navItems:readonly NavItem[]=[
  ['/app/overview','Overview',LayoutDashboard],
  ['/app/payments','Payments',CreditCard],
  ['/app/checkouts','Checkouts',WalletCards],
  ['/app/payment-channels','Payment Channels',PlugZap],
  ['/app/account','Account',Building2],
];

type SessionState={session:OperatorSession|null;loading:boolean;refresh:()=>Promise<void>;setSession:(value:OperatorSession|null)=>void};
const SessionContext=React.createContext<SessionState|null>(null);
function useSession(){const value=React.useContext(SessionContext);if(!value)throw new Error('SessionContext unavailable');return value}

function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'active'}){return <span className={`badge ${tone}`}>{children}</span>}
function VeroxBrand(){return <div className="brand"><img src="/verox-mark.svg" alt=""/><div><strong>VEROX</strong><small>MERCHANT</small></div></div>}
function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <section className="page-intro"><div><span className="eyebrow">{eyebrow??'MERCHANT PLATFORM'}</span><h1>{title}</h1><p>{description}</p></div>{action}</section>}
function Notice({title,detail,tone='info'}:{title:string;detail:string;tone?:'info'|'warning'|'danger'}){return <div className={tone==='warning'||tone==='danger'?'contract-banner':'data-notice'}><AlertTriangle size={16}/><div><strong>{title}</strong><span>{detail}</span></div></div>}

function errorMessage(error:unknown):string{
  if(error instanceof PlatformCsrfUnavailableError)return error.message;
  if(error instanceof PlatformApiError){
    if(error.status===401)return 'A sessão expirou ou já não é válida. Inicie sessão novamente.';
    if(error.status===403)return error.code==='INVALID_CSRF_TOKEN'?'O pedido foi recusado porque o token CSRF não é válido.':error.message;
    if(error.status===409)return 'O estado do pagamento mudou e a operação já não é permitida. Atualize o pagamento.';
    if(error.status===429)return error.retryAfter?`Limite temporário atingido. Tente novamente após ${error.retryAfter}.`:'Limite temporário atingido. Tente novamente mais tarde.';
    return error.message;
  }
  return 'Ocorreu um erro inesperado.';
}

function SessionProvider({children}:{children:React.ReactNode}){
  const[session,setSession]=React.useState<OperatorSession|null>(null);
  const[loading,setLoading]=React.useState(true);
  const refresh=React.useCallback(async()=>{try{setSession(await platformApi.session())}catch(error){if(error instanceof PlatformApiError&&error.status===401)setSession(null);else throw error}},[]);
  React.useEffect(()=>{refresh().catch(()=>setSession(null)).finally(()=>setLoading(false))},[refresh]);
  return <SessionContext.Provider value={{session,loading,refresh,setSession}}>{children}</SessionContext.Provider>;
}

function Login(){
  const{setSession}=useSession();
  const[username,setUsername]=React.useState('owen');const[password,setPassword]=React.useState('');
  const[busy,setBusy]=React.useState(false);const[error,setError]=React.useState<string|null>(null);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError(null);try{setSession(await platformApi.login(username.trim(),password))}catch(err){setError(err instanceof PlatformApiError&&err.status===401?'Credenciais inválidas.':errorMessage(err))}finally{setBusy(false)}}
  return <main className="login-page"><section className="login-card"><VeroxBrand/><div className="login-copy"><span className="eyebrow">OPERATOR ACCESS</span><h1>Merchant Platform</h1><p>Entre com a credencial de operador VEROX. A sessão permanece no servidor.</p></div><form className="login-form" onSubmit={submit}><label><span>Utilizador</span><input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required maxLength={160}/></label><label><span>Palavra-passe</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required maxLength={255}/></label>{error&&<Notice tone="danger" title="Não foi possível iniciar sessão" detail={error}/>}<button className="primary-action login-submit" disabled={busy||!username.trim()||!password}>{busy?'A entrar…':'Entrar'}<ArrowRight size={16}/></button></form><div className="login-security"><ShieldCheck size={16}/><span>VEROX_OPERATOR_SESSION é HttpOnly. Nenhuma Merchant API key é armazenada no browser.</span></div></section></main>
}

function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){const{session}=useSession();return <aside className={`sidebar ${open?'open':''}`}><div className="sidebar-head"><VeroxBrand/><button className="icon-btn mobile-close" onClick={onClose} aria-label="Fechar navegação"><X size={18}/></button></div><div className="merchant-context"><span>MERCHANT</span><strong>{session?.merchantName}</strong><small>{session?.environment} · {session?.operatorDisplayName}</small></div><nav><div className="nav-group"><span>OPERATIONS</span>{navItems.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={onClose} className={({isActive})=>isActive?'active':''}><Icon size={17}/>{label}</NavLink>)}</div></nav><div className="sidebar-foot"><div className="truth"><ShieldCheck size={17}/><div><strong>VEROX Server</strong><small>Payment truth authority</small></div></div></div></aside>}

function Topbar({onMenu}:{onMenu:()=>void}){const nav=useNavigate();const{session,setSession}=useSession();const[q,setQ]=React.useState('');const[logoutError,setLogoutError]=React.useState<string|null>(null);async function logout(){setLogoutError(null);try{await platformApi.logout();setSession(null)}catch(err){setLogoutError(errorMessage(err))}}return <><header className="topbar"><button className="icon-btn menu-btn" onClick={onMenu} aria-label="Abrir navegação"><Menu size={18}/></button><form className="global-search" onSubmit={e=>{e.preventDefault();const id=q.trim();if(id)nav('/app/payments/'+encodeURIComponent(id))}}><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Abrir pagamento por pay_* ID" aria-label="Payment ID"/><kbd>↵</kbd></form><Badge tone="active">{session?.environment}</Badge><NavLink to="/app/account" className="avatar">{session?.operatorDisplayName.split(/\s+/).map(v=>v[0]).slice(0,2).join('').toUpperCase()}</NavLink><button className="icon-btn" onClick={logout} aria-label="Terminar sessão" title="Terminar sessão"><LogOut size={17}/></button></header>{logoutError&&<div className="top-error"><span>{logoutError}</span></div>}</>}

function LoadingPanel({label='A carregar…'}:{label?:string}){return <article className="panel"><div className="empty"><RefreshCw className="spin" size={20}/><strong>{label}</strong></div></article>}
function EmptyPanel({title,detail}:{title:string;detail:string}){return <article className="panel"><div className="empty"><strong>{title}</strong><p>{detail}</p></div></article>}
function PaymentBadge({value}:{value:Payment['effectiveStatus']}){const semantic=paymentSemantic(value);return <Badge tone={semantic.tone}>{semantic.label}</Badge>}
function money(amount:string,currency:string){return `${amount} ${currency}`}
function date(value:string|null|undefined){if(!value)return '—';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString('pt-MZ')}

function PaymentsTable({items}:{items:PaymentListItem[]}){const nav=useNavigate();return <div className="table-wrap"><table><thead><tr><th>Payment</th><th>Reference</th><th>Amount</th><th>Provider</th><th>Effective state</th><th>Attention</th><th>Created</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>nav(`/app/payments/${encodeURIComponent(item.id)}`)}><td><code>{item.id}</code></td><td>{item.externalReference}</td><td>{money(item.amount,item.currency)}</td><td>{item.provider??'—'}</td><td><PaymentBadge value={item.effectiveStatus}/></td><td>{item.attentionRequired?<Badge tone="warning">Required</Badge>:<span>—</span>}</td><td>{date(item.createdAt)}</td></tr>)}</tbody></table></div>}

function Overview(){const[recent,setRecent]=React.useState<PaymentPage|null>(null);const[attention,setAttention]=React.useState<PaymentPage|null>(null);const[confirmed,setConfirmed]=React.useState<PaymentPage|null>(null);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState<string|null>(null);const load=React.useCallback(async()=>{setLoading(true);setError(null);try{const[r,a,c]=await Promise.all([platformApi.payments({page:0,size:8}),platformApi.payments({attentionRequired:true,page:0,size:1}),platformApi.payments({status:'CONFIRMED',page:0,size:1})]);setRecent(r);setAttention(a);setConfirmed(c)}catch(err){setError(errorMessage(err))}finally{setLoading(false)}},[]);React.useEffect(()=>{load()},[load]);return <div className="page-stack"><PageHeader title="Payment operations" description="Estado operacional diretamente do VEROX Server. O frontend não reconstrói payment truth." action={<button className="primary-action" onClick={load}><RefreshCw size={15}/>Atualizar</button>}/>{error&&<Notice tone="warning" title="Dados indisponíveis" detail={error}/>}<section className="kpi-grid"><article className="kpi"><span>Payments</span><strong>{recent?.totalItems??'—'}</strong><small>Current environment</small></article><article className="kpi"><span>Needs attention</span><strong>{attention?.totalItems??'—'}</strong><small className="warning">Backend attention_required</small></article><article className="kpi"><span>Confirmed</span><strong>{confirmed?.totalItems??'—'}</strong><small className="success">Core status CONFIRMED</small></article><article className="kpi"><span>Backend</span><strong className="kpi-server">LIVE</strong><small>{PLATFORM_BACKEND_ORIGIN.replace('https://','')}</small></article></section>{loading?<LoadingPanel label="A carregar pagamentos reais…"/>:recent&&recent.items.length?<article className="panel"><div className="panel-head"><div><span className="eyebrow">RECENT PAYMENTS</span><h2>Atividade recente</h2></div><NavLink to="/app/payments">Ver todos <ChevronRight size={15}/></NavLink></div><PaymentsTable items={recent.items}/></article>:<EmptyPanel title="Ainda não existem pagamentos" detail="O VEROX Server não devolveu pagamentos neste ambiente."/>}</div>}

function Payments(){const[page,setPage]=React.useState(0);const[status,setStatus]=React.useState<PaymentCoreState|''>('');const[attention,setAttention]=React.useState<'all'|'yes'>('all');const[data,setData]=React.useState<PaymentPage|null>(null);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState<string|null>(null);const load=React.useCallback(async()=>{setLoading(true);setError(null);try{setData(await platformApi.payments({page,size:20,status:status||undefined,attentionRequired:attention==='yes'?true:undefined}))}catch(err){setError(errorMessage(err))}finally{setLoading(false)}},[page,status,attention]);React.useEffect(()=>{load()},[load]);return <div className="page-stack"><PageHeader title="Payments" description="Feed merchant-scoped com estados reais, paginação e filtros suportados pelo backend." action={<button className="primary-action" onClick={load}><RefreshCw size={15}/>Atualizar</button>}/><div className="filterbar"><select value={status} onChange={e=>{setPage(0);setStatus(e.target.value as PaymentCoreState|'')}}><option value="">All states</option>{['PENDING','VERIFYING','CONFIRMED','REVIEW_REQUIRED','FAILED','EXPIRED'].map(value=><option key={value} value={value}>{value}</option>)}</select><select value={attention} onChange={e=>{setPage(0);setAttention(e.target.value as 'all'|'yes')}}><option value="all">All payments</option><option value="yes">Attention required</option></select></div>{error&&<Notice tone="warning" title="Não foi possível carregar payments" detail={error}/>} {loading?<LoadingPanel/>:data&&data.items.length?<article className="panel"><PaymentsTable items={data.items}/><div className="pagination"><button disabled={data.page<=0} onClick={()=>setPage(p=>Math.max(0,p-1))}><ChevronLeft size={15}/>Anterior</button><span>Página {data.page+1} de {Math.max(data.totalPages,1)} · {data.totalItems} pagamentos</span><button disabled={data.page+1>=data.totalPages} onClick={()=>setPage(p=>p+1)}>Seguinte<ChevronRight size={15}/></button></div></article>:<EmptyPanel title="Nenhum pagamento encontrado" detail="Não existem pagamentos para os filtros selecionados."/>}</div>}

function ManualAcceptanceDialog({payment,onClose,onAccepted}:{payment:Payment;onClose:()=>void;onAccepted:()=>Promise<void>}){const[reason,setReason]=React.useState('');const[busy,setBusy]=React.useState(false);const[error,setError]=React.useState<string|null>(null);async function accept(){setBusy(true);setError(null);try{await platformApi.acceptManually(payment.id,reason);await onAccepted();onClose()}catch(err){setError(errorMessage(err));if(err instanceof PlatformApiError&&err.status===409)await onAccepted().catch(()=>{})}finally{setBusy(false)}}return <div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="manual-title"><button className="modal-close" onClick={onClose} aria-label="Fechar"><X size={18}/></button><span className="eyebrow">PILOT CONTROL</span><h2 id="manual-title">Accept manually</h2><p>Esta ação regista uma aceitação manual auditada. Não representa verificação automática e não força o core status para CONFIRMED.</p><dl><div><dt>Payment</dt><dd><code>{payment.id}</code></dd></div><div><dt>Reference</dt><dd>{payment.externalReference}</dd></div><div><dt>Amount</dt><dd>{money(payment.amount,payment.currency)}</dd></div><div><dt>Core status</dt><dd>{payment.status}</dd></div></dl><label className="modal-field"><span>Reason (optional)</span><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={255} placeholder="Motivo operacional da aceitação manual"/><small>{reason.length}/255</small></label>{error&&<Notice tone="warning" title="A operação não foi concluída" detail={error}/>}<div className="modal-actions"><button className="secondary-action" onClick={onClose} disabled={busy}>Cancelar</button><button className="primary-action" onClick={accept} disabled={busy}>{busy?'A registar…':'Accept manually'}</button></div></section></div>}

function PaymentDetail(){const{id=''}=useParams();const[payment,setPayment]=React.useState<Payment|null>(null);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState<string|null>(null);const[dialog,setDialog]=React.useState(false);const load=React.useCallback(async()=>{setLoading(true);setError(null);try{setPayment(await platformApi.payment(id))}catch(err){setError(errorMessage(err))}finally{setLoading(false)}},[id]);React.useEffect(()=>{load()},[load]);if(loading)return <div className="page-stack"><PageHeader title={id} description="A carregar payment truth…"/><LoadingPanel/></div>;return <div className="page-stack"><PageHeader eyebrow="PAYMENT DETAIL" title={payment?.externalReference||id} description="Core status e effective status permanecem semanticamente separados." action={<button className="primary-action" onClick={load}><RefreshCw size={15}/>Atualizar</button>}/>{error&&<Notice tone="warning" title="Payment indisponível" detail={error}/>} {payment&&<><section className="detail-grid"><article className="panel summary-card"><span>Amount</span><strong>{money(payment.amount,payment.currency)}</strong><dl><div><dt>Payment ID</dt><dd><code>{payment.id}</code></dd></div><div><dt>Checkout</dt><dd><code>{payment.checkoutSessionId}</code></dd></div><div><dt>Provider</dt><dd>{payment.provider??'—'}</dd></div><div><dt>Reference</dt><dd>{payment.externalReference}</dd></div></dl></article><article className="panel summary-card"><span>Payment truth</span><dl><div><dt>Effective state</dt><dd><PaymentBadge value={payment.effectiveStatus}/></dd></div><div><dt>Core status</dt><dd><PaymentBadge value={payment.status}/></dd></div><div><dt>Confirmed at</dt><dd>{date(payment.confirmedAt)}</dd></div><div><dt>Manual acceptance</dt><dd>{date(payment.manuallyAcceptedAt)}</dd></div></dl>{payment.effectiveStatus==='MANUALLY_ACCEPTED'&&<Notice tone="warning" title="Accepted manually" detail="Este resultado preserva proveniência manual. Não é equivalente a confirmação automática."/>}</article></section><article className="panel operational-action"><div><span className="eyebrow">OPERATIONAL ACTION</span><h2>Manual acceptance</h2><p>Disponível apenas para PENDING ou REVIEW_REQUIRED. O backend continua a ser a autoridade final.</p></div>{canAcceptManually(payment)?<button className="primary-action" onClick={()=>setDialog(true)}>Accept manually</button>:<Badge tone={payment.effectiveStatus==='MANUALLY_ACCEPTED'?'warning':'neutral'}>{payment.effectiveStatus==='MANUALLY_ACCEPTED'?'Already accepted':'Not eligible'}</Badge>}</article>{dialog&&<ManualAcceptanceDialog payment={payment} onClose={()=>setDialog(false)} onAccepted={load}/>}</>}</div>}

function PaymentChannels(){const[channels,setChannels]=React.useState<PaymentChannel[]|null>(null);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState<string|null>(null);const load=React.useCallback(async()=>{setLoading(true);setError(null);try{setChannels(await platformApi.paymentChannels())}catch(err){setError(errorMessage(err))}finally{setLoading(false)}},[]);React.useEffect(()=>{load()},[load]);const logo=(provider:string)=>{const key=provider.toUpperCase();if(key.includes('MPESA')||key.includes('M_PESA'))return'/providers/m-pesa.png';if(key.includes('EMOLA')||key.includes('E_MOLA'))return'/providers/e-mola.png';if(key.includes('MILLENNIUM'))return'/providers/millennium-bim.png';return null};return <div className="page-stack"><PageHeader title="Payment Channels" description="Canais e dados de receção apresentados exclusivamente a partir do backend." action={<button className="primary-action" onClick={load}><RefreshCw size={15}/>Atualizar</button>}/>{error&&<Notice tone="warning" title="Canais indisponíveis" detail={error}/>} {loading?<LoadingPanel/>:channels&&channels.length?<section className="channel-grid">{channels.map(channel=><article className="channel-card" key={channel.provider}><header><span className="provider-logo">{logo(channel.provider)?<img src={logo(channel.provider)!} alt=""/>:<b>{channel.displayName.slice(0,2)}</b>}</span><div><h2>{channel.displayName}</h2><span>{channel.kind}</span></div><Badge tone={channel.status==='ACTIVE'?'success':'neutral'}>{channel.status}</Badge></header><dl><div><dt>Recipient</dt><dd>{channel.recipientDisplay??'—'}</dd></div><div><dt>Name</dt><dd>{channel.recipientName??'—'}</dd></div><div><dt>Updated</dt><dd>{date(channel.updatedAt)}</dd></div></dl>{channel.instructions&&<p className="channel-instructions">{channel.instructions}</p>}</article>)}</section>:<EmptyPanel title="Nenhum payment channel disponível" detail="O backend não devolveu canais para este merchant/environment."/>}</div>}

function Checkouts(){return <div className="page-stack"><PageHeader title="Checkouts" description="A Merchant Platform ainda não possui um contrato /platform/v1 para listar checkout sessions."/><Notice tone="warning" title="BACKEND GAP — DO NOT FAKE" detail="O Hosted Checkout público e os Merchant API checkout contracts existem, mas não há um endpoint browser-session de coleção/detail para esta tela. Nenhum fixture será apresentado como produção."/><EmptyPanel title="Checkout feed não disponível" detail="Esta tela ficará pronta para integração quando o backend expuser o contrato Platform correspondente."/></div>}

function Account(){const{session,refresh}=useSession();const[account,setAccount]=React.useState<OperatorSession|null>(null);const[error,setError]=React.useState<string|null>(null);React.useEffect(()=>{platformApi.account().then(setAccount).catch(err=>setError(errorMessage(err)))},[]);return <div className="page-stack"><PageHeader title="Account" description="Identidade do operador e merchant carregada da sessão real do VEROX Server." action={<button className="primary-action" onClick={()=>refresh()}><RefreshCw size={15}/>Refresh session</button>}/>{error&&<Notice tone="warning" title="Account indisponível" detail={error}/>}<section className="detail-grid"><article className="panel account-card"><span className="eyebrow">OPERATOR</span><h2>{account?.operatorDisplayName??session?.operatorDisplayName}</h2><dl><div><dt>Operator ID</dt><dd><code>{account?.operatorId??session?.operatorId}</code></dd></div><div><dt>Environment</dt><dd><Badge tone="active">{account?.environment??session?.environment}</Badge></dd></div></dl></article><article className="panel account-card"><span className="eyebrow">MERCHANT</span><h2>{account?.merchantName??session?.merchantName}</h2><dl><div><dt>Merchant ID</dt><dd><code>{account?.merchantId??session?.merchantId}</code></dd></div><div><dt>Authority</dt><dd>VEROX Server</dd></div></dl></article></section></div>}

function AppShell(){const[open,setOpen]=React.useState(false);return <div className="app-shell"><Sidebar open={open} onClose={()=>setOpen(false)}/><div className="workspace"><Topbar onMenu={()=>setOpen(true)}/><main className="content"><Routes><Route path="/app/overview" element={<Overview/>}/><Route path="/app/payments" element={<Payments/>}/><Route path="/app/payments/:id" element={<PaymentDetail/>}/><Route path="/app/checkouts" element={<Checkouts/>}/><Route path="/app/payment-channels" element={<PaymentChannels/>}/><Route path="/app/account" element={<Account/>}/><Route path="/app" element={<Navigate to="/app/overview" replace/>}/><Route path="*" element={<Navigate to="/app/overview" replace/>}/></Routes></main></div>{open&&<button className="scrim" aria-label="Fechar navegação" onClick={()=>setOpen(false)}/>}</div>}

function Root(){const{session,loading}=useSession();if(loading)return <main className="login-page"><section className="login-card"><VeroxBrand/><div className="login-copy"><h1>A validar sessão…</h1><p>VEROX Server é a autoridade de sessão.</p></div></section></main>;return session?<AppShell/>:<Login/>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><SessionProvider><Root/></SessionProvider></BrowserRouter></React.StrictMode>);
