import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,NavLink,Navigate,Route,Routes,useNavigate,useParams} from 'react-router-dom';
import {Activity,AlertTriangle,ArrowRight,Bell,BookOpen,CheckCircle2,ChevronRight,CircleHelp,Code2,CreditCard,FileClock,KeyRound,LayoutDashboard,ListChecks,Menu,RefreshCw,Search,Settings,ShieldCheck,Users,WalletCards,Webhook,X,Copy,EyeOff,Building2,SlidersHorizontal,PlugZap,Clock3} from 'lucide-react';
import './styles.css';
import type {Environment,ProviderId,TimelineEvent} from './domain';
import {fallbackApiKeys,fallbackChannels,fallbackCheckouts,fallbackMerchant,fallbackPayments,fallbackReviews,fallbackTeam,fallbackTimeline,fallbackWebhooks,fallbackDeliveries} from './data';

const money=(n:number)=>new Intl.NumberFormat('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' MZN';
const providerNames:Record<ProviderId,string>={mpesa:'M-Pesa',emola:'e-Mola','millennium-bim':'Millennium bim'};
const providerAssets:Record<ProviderId,string>={mpesa:'/providers/m-pesa.png',emola:'/providers/e-mola.png','millennium-bim':'/providers/millennium-bim.png'};
const navGroups=[
 {label:'OPERATIONS',items:[['/app/overview','Overview',LayoutDashboard],['/app/payments','Payments',CreditCard],['/app/checkouts','Checkouts',WalletCards],['/app/reviews','Reviews',ListChecks]]},
 {label:'PAYMENT INFRASTRUCTURE',items:[['/app/payment-channels','Payment Channels',PlugZap]]},
 {label:'DEVELOPERS',items:[['/app/developers','Integration',Code2],['/app/api-keys','API Keys',KeyRound],['/app/webhooks','Webhooks',Webhook],['/app/api-logs','API Logs',FileClock]]},
 {label:'ORGANIZATION',items:[['/app/team','Team',Users],['/app/account','Account',Building2],['/app/settings','Settings',Settings]]},
];

function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'active'}){return <span className={`badge ${tone}`}>{children}</span>}
function stateTone(s:string){if(['ACTIVE','READY','CONFIRMED','COMPLETED','DELIVERED'].includes(s))return 'success' as const;if(['VERIFYING','EVIDENCE_RECEIVED','CONFIGURED','TEST_READY','DELIVERING'].includes(s))return 'active' as const;if(['REVIEW_REQUIRED','UNDER_REVIEW','RETRYING','VERIFICATION_REQUIRED','REQUIRES_ACTION'].includes(s))return 'warning' as const;if(['NOT_VERIFIED','FAILED','DISCONNECTED','DISABLED','REVOKED'].includes(s))return 'danger' as const;return 'neutral' as const}
function ProviderMark({id}:{id:ProviderId}){return <span className="provider-logo"><img src={providerAssets[id]} alt="" onError={e=>{e.currentTarget.style.display='none'}}/><b>{providerNames[id].slice(0,2)}</b></span>}
function VeroxBrand(){return <div className="brand"><img src="/verox-mark.svg" alt=""/><div><strong>VEROX</strong><small>MERCHANT</small></div></div>}
function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <section className="page-intro"><div><span className="eyebrow">{eyebrow??'MERCHANT PLATFORM'}</span><h1>{title}</h1><p>{description}</p></div>{action}</section>}
function DataNotice(){return <div className="data-notice"><Activity size={16}/><div><strong>TEST preview data</strong><span>Structured frontend fallback only. Replace with Merchant API responses when the required collection contracts are available.</span></div></div>}
function EmptyState({title,detail}:{title:string;detail:string}){return <div className="empty"><Activity size={22}/><strong>{title}</strong><p>{detail}</p></div>}
function EnvironmentSwitcher({value,onChange}:{value:Environment;onChange:(v:Environment)=>void}){return <div className="environment-switch" aria-label="Environment selector">{(['TEST','LIVE'] as Environment[]).map(v=><button key={v} className={value===v?'selected':''} onClick={()=>onChange(v)}>{v}</button>)}</div>}

function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){return <aside className={`sidebar ${open?'open':''}`}><div className="sidebar-head"><VeroxBrand/><button className="icon-btn mobile-close" onClick={onClose} aria-label="Close navigation"><X size={18}/></button></div><div className="merchant-context"><span>ORGANIZATION</span><strong>{fallbackMerchant.name}</strong><small>{fallbackMerchant.lifecycle.replaceAll('_',' ')}</small></div><nav>{navGroups.map(g=><div className="nav-group" key={g.label}><span>{g.label}</span>{g.items.map(([to,label,Icon])=><NavLink key={String(to)} to={String(to)} onClick={onClose} className={({isActive})=>isActive?'active':''}><Icon size={17}/>{label}</NavLink>)}</div>)}</nav><div className="sidebar-foot"><div className="truth"><ShieldCheck size={17}/><div><strong>VEROX Server</strong><small>Payment truth authority</small></div></div><a href="https://github.com/rightware-corporations/verox-system" target="_blank" rel="noreferrer"><BookOpen size={16}/>Documentation</a><button disabled title="Support channel is not configured"><CircleHelp size={16}/>Support</button></div></aside>}
function Topbar({env,onEnv,onMenu}:{env:Environment;onEnv:(v:Environment)=>void;onMenu:()=>void}){const nav=useNavigate();const[q,setQ]=React.useState('');return <header className="topbar"><button className="icon-btn menu-btn" onClick={onMenu}><Menu size={18}/></button><form className="global-search" onSubmit={e=>{e.preventDefault();if(q.trim())nav('/app/payments?q='+encodeURIComponent(q.trim()))}}><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search payment or reference"/><kbd>↵</kbd></form><EnvironmentSwitcher value={env} onChange={onEnv}/><button className="icon-btn" disabled title="Notifications backend not configured"><Bell size={17}/></button><NavLink to="/app/account" className="avatar">MS</NavLink></header>}
function KPI({label,value,helper,tone}:{label:string;value:string;helper:string;tone?:string}){return <article className="kpi"><span>{label}</span><strong>{value}</strong><small className={tone}>{helper}</small></article>}
function SystemHealth(){return <article className="panel"><div className="panel-head"><div><span className="eyebrow">SYSTEM HEALTH</span><h2>Operational readiness</h2></div></div><div className="health-list">{[['Merchant API','Ready','success'],['Webhook endpoint','Configured','active'],['M-Pesa','Connected','success'],['e-Mola','Backend enablement','warning'],['Millennium bim','Not configured','neutral']].map(([a,b,t])=><div className="health-row" key={a}><span className={`status-dot ${t}`}/><div><strong>{a}</strong><small>{b}</small></div></div>)}</div></article>}

function Overview({env}:{env:Environment}){const data=fallbackPayments.filter(p=>p.environment===env);const confirmed=data.filter(p=>p.state==='CONFIRMED');const review=data.filter(p=>p.state==='REVIEW_REQUIRED');return <div className="page-stack"><PageHeader eyebrow="MERCHANT CONTROL ROOM" title="Payment operations" description="See payment truth, exceptions and integration health without mixing checkout state with authoritative payment state." action={<NavLink className="primary-action" to="/app/checkouts">Create checkout <ArrowRight size={16}/></NavLink>}/><DataNotice/><section className="kpi-grid"><KPI label="Verified volume" value={money(confirmed.reduce((a,p)=>a+p.amount,0))} helper="TEST preview"/><KPI label="Payments" value={String(data.length)} helper="Current environment"/><KPI label="Confirmed" value={String(confirmed.length)} helper="Server-authoritative state" tone="success"/><KPI label="Needs attention" value={String(review.length)} helper="Review required" tone="warning"/></section><section className="overview-layout"><article className="panel"><div className="panel-head"><div><span className="eyebrow">PAYMENT ACTIVITY</span><h2>Recent truth changes</h2></div><NavLink to="/app/payments">View all <ChevronRight size={14}/></NavLink></div><div className="activity-chart" aria-label="Preview activity chart"><i/><i/><i/><i/><i/><i/><i/><i/></div><PaymentsTable rows={data.slice(0,3)} compact/></article><aside className="stack"><article className="panel attention"><div className="panel-head"><div><span className="eyebrow">NEEDS ATTENTION</span><h2>Operational exceptions</h2></div></div><NavLink to="/app/reviews"><AlertTriangle size={16}/><div><strong>{review.length} payment requires review</strong><span>Inspect the review queue without changing payment truth.</span></div><ChevronRight size={16}/></NavLink><NavLink to="/app/payment-channels"><PlugZap size={16}/><div><strong>2 channels require setup</strong><span>e-Mola and Millennium bim are not operational yet.</span></div><ChevronRight size={16}/></NavLink></article><SystemHealth/></aside></section></div>}
function PaymentsTable({rows,compact=false}:{rows:typeof fallbackPayments;compact?:boolean}){const nav=useNavigate();return <div className={`table-wrap ${compact?'compact':''}`}><table><thead><tr><th>Payment</th><th>Reference</th><th>Amount</th><th>Provider</th><th>Payment state</th><th>Verification</th><th>Created</th></tr></thead><tbody>{rows.map(p=><tr key={p.id} onClick={()=>nav('/app/payments/'+p.id)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')nav('/app/payments/'+p.id)}}><td><code>{p.id}</code></td><td>{p.externalReference}</td><td><strong>{money(p.amount)}</strong></td><td><span className="provider-cell"><ProviderMark id={p.provider}/>{providerNames[p.provider]}</span></td><td><Badge tone={stateTone(p.state)}>{p.state.replaceAll('_',' ')}</Badge></td><td>{p.verificationState}</td><td>{p.createdAt}</td></tr>)}</tbody></table></div>}
function PaymentsPage({env}:{env:Environment}){const params=new URLSearchParams(location.search);const[q,setQ]=React.useState(params.get('q')??'');const[status,setStatus]=React.useState('ALL');const[provider,setProvider]=React.useState('ALL');const rows=fallbackPayments.filter(p=>p.environment===env&&[p.id,p.externalReference].join(' ').toLowerCase().includes(q.toLowerCase())&&(status==='ALL'||p.state===status)&&(provider==='ALL'||p.provider===provider));return <div className="page-stack"><PageHeader title="Payments" description="Operational payment records. Payment state and webhook delivery remain separate concepts."/><DataNotice/><div className="filterbar"><label><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Payment ID or reference"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>CONFIRMED</option><option>VERIFYING</option><option>REVIEW_REQUIRED</option><option>NOT_VERIFIED</option></select><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="ALL">All providers</option><option value="mpesa">M-Pesa</option><option value="emola">e-Mola</option><option value="millennium-bim">Millennium bim</option></select><button onClick={()=>{setQ('');setStatus('ALL');setProvider('ALL')}}><RefreshCw size={14}/>Reset</button></div><article className="panel"><PaymentsTable rows={rows}/>{!rows.length&&<EmptyState title="No payments match these filters" detail="Change the search or filters. No payment state has been changed."/>}</article></div>}
function TrustTimeline({events}:{events:TimelineEvent[]}){return <ol className="timeline">{events.map(e=><li key={e.id} className={e.state}><span className="timeline-node"/><time>{e.timestamp}</time><div><strong>{e.title}</strong><p>{e.detail}</p>{e.relatedId&&<code>{e.relatedId}</code>}</div></li>)}</ol>}
function PaymentDetail(){const{id}=useParams();const p=fallbackPayments.find(x=>x.id===id);if(!p)return <div className="page-stack"><PageHeader title="Payment not available" description="This payment is not present in the current frontend data source."/><EmptyState title="Payment not found" detail="Use Payments to return to the operational list."/></div>;return <div className="page-stack"><PageHeader eyebrow="PAYMENT TRUTH RECORD" title={p.id} description="Authoritative payment state and related operational events." action={<Badge tone={stateTone(p.state)}>{p.state}</Badge>}/><DataNotice/><section className="detail-grid"><article className="panel summary-card"><span>Amount</span><strong>{money(p.amount)}</strong><dl><div><dt>Reference</dt><dd>{p.externalReference}</dd></div><div><dt>Provider</dt><dd>{providerNames[p.provider]}</dd></div><div><dt>Checkout</dt><dd>{p.checkoutId}</dd></div><div><dt>Environment</dt><dd>{p.environment}</dd></div><div><dt>Created</dt><dd>{p.createdAt}</dd></div><div><dt>Verified</dt><dd>{p.verifiedAt??'—'}</dd></div></dl></article><article className="panel timeline-panel"><div className="panel-head"><div><span className="eyebrow">VERIFIED TRUTH</span><h2>Trust timeline</h2></div></div><TrustTimeline events={p.id==='pay_demo_84F2'?fallbackTimeline:fallbackTimeline.slice(0,4)}/></article></section></div>}

function Checkouts({env}:{env:Environment}){const nav=useNavigate();const rows=fallbackCheckouts.filter(c=>c.environment===env);return <div className="page-stack"><PageHeader title="Checkout sessions" description="Checkout lifecycle is intentionally separate from payment truth."/><DataNotice/><article className="panel"><div className="table-wrap"><table><thead><tr><th>Checkout</th><th>Reference</th><th>Amount</th><th>Checkout state</th><th>Payment state</th><th>Created</th><th>Expires</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} onClick={()=>c.paymentId&&nav('/app/payments/'+c.paymentId)} className={c.paymentId?'clickable':'static'}><td><code>{c.id}</code></td><td>{c.externalReference}</td><td>{money(c.amount)}</td><td><Badge tone={stateTone(c.state)}>{c.state.replaceAll('_',' ')}</Badge></td><td>{c.paymentState?<Badge tone={stateTone(c.paymentState)}>{c.paymentState.replaceAll('_',' ')}</Badge>:'—'}</td><td>{c.createdAt}</td><td>{c.expiresAt}</td></tr>)}</tbody></table></div></article></div>}
function Reviews({env}:{env:Environment}){const rows=fallbackReviews.filter(r=>r.environment===env);return <div className="page-stack"><PageHeader title="Review queue" description="Transactions requiring attention. Review does not grant the merchant authority to confirm payment."/><DataNotice/><section className="review-grid">{rows.map(r=><article className="review-card" key={r.paymentId}><div><span className="eyebrow">REVIEW REQUIRED</span><h2>{r.externalReference}</h2><code>{r.paymentId}</code></div><strong>{money(r.amount)}</strong><div className="review-meta"><span>{providerNames[r.provider]}</span><span>{r.age}</span><Badge tone="warning">{r.state.replaceAll('_',' ')}</Badge></div><p>{r.reason}</p><NavLink to={'/app/payments/'+r.paymentId}>Inspect payment <ArrowRight size={14}/></NavLink></article>)}{!rows.length&&<EmptyState title="No reviews require attention" detail="There are no review items in this environment."/>}</section></div>}
function PaymentChannels({env}:{env:Environment}){const rows=fallbackChannels.filter(c=>c.environment===env);return <div className="page-stack"><PageHeader title="Payment channels" description="Configure the destinations and verification connectivity that make each provider operational."/><DataNotice/><section className="channel-grid">{rows.map(c=><article className="channel-card" key={c.provider}><header><ProviderMark id={c.provider}/><div><h2>{c.name}</h2><span>{c.environment}</span></div><Badge tone={stateTone(c.state)}>{c.state.replaceAll('_',' ')}</Badge></header><dl><div><dt>Destination</dt><dd>{c.recipient??'Not configured'}</dd></div><div><dt>Verification health</dt><dd>{c.health}</dd></div><div><dt>Last activity</dt><dd>{c.lastActivity??'—'}</dd></div></dl>{c.action?<button disabled title="Requires backend capability">{c.action}</button>:<span className="safe-state"><CheckCircle2 size={15}/>No action required</span>}</article>)}</section></div>}

function Integration({env}:{env:Environment}){const steps:[string,boolean][]=[['Organization created',true],['TEST environment available',true],['Payment channel configured',true],['API key created',true],['Webhook configured',true],['Test checkout created',true],['First verified test payment',true],['Request LIVE access',false],['LIVE activated',false]];return <div className="page-stack"><PageHeader title="Integration & go-live" description="A controlled path from TEST readiness to LIVE operations."/><section className="integration-layout"><article className="panel progress-card"><div className="progress-summary"><span className="eyebrow">CURRENT ENVIRONMENT</span><strong>{env}</strong><p>{steps.filter(s=>s[1]).length} of {steps.length} readiness steps represented.</p></div><div className="step-list">{steps.map(([label,done],i)=><div className={done?'done':''} key={label}><span>{done?<CheckCircle2 size={16}/>:i===7?<Clock3 size={16}/>:i+1}</span><strong>{label}</strong><small>{done?'Completed in TEST preview':'Pending backend/product workflow'}</small></div>)}</div></article><SystemHealth/></section></div>}
function ApiKeys({env}:{env:Environment}){const keys=fallbackApiKeys.filter(k=>k.environment===env);const[showInfo,setShowInfo]=React.useState(false);return <div className="page-stack"><PageHeader title="API keys" description="Server credentials are managed conservatively: full secrets are shown once at creation, never permanently revealed from the browser." action={<button className="primary-action" disabled title="Merchant-facing API key lifecycle endpoint is not available"><KeyRound size={16}/>Create API key</button>}/><DataNotice/>{showInfo&&<div className="security-callout"><ShieldCheck size={17}/><span>No secret is stored in this frontend fallback. Key creation/revoke/rotate require backend lifecycle endpoints.</span></div>}<article className="panel"><div className="key-list">{keys.map(k=><div className="key-row" key={k.id}><div className="key-icon"><KeyRound size={18}/></div><div className="key-main"><strong>{k.name}</strong><code>{k.masked}</code><span>Created {k.createdAt} · Last used {k.lastUsed??'Never'}</span></div><Badge tone={stateTone(k.state)}>{k.state}</Badge><div className="row-actions"><button onClick={()=>navigator.clipboard.writeText(k.prefix)}><Copy size={14}/>Copy prefix</button><button onClick={()=>setShowInfo(v=>!v)}><EyeOff size={14}/>Security</button><button disabled title="Backend rotate/revoke contract required">•••</button></div></div>)}</div></article></div>}
function WebhooksPage({env}:{env:Environment}){const endpoints=fallbackWebhooks.filter(w=>w.environment===env);const deliveries=fallbackDeliveries.filter(d=>d.environment===env);return <div className="page-stack"><PageHeader title="Webhooks" description="Keep VEROX payment truth separate from delivery state at the merchant endpoint."/><DataNotice/><section className="webhook-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">ENDPOINT</span><h2>Delivery destination</h2></div></div>{endpoints.map(w=><div className="endpoint" key={w.id}><div><code>{w.url}</code><span>{w.events.join(', ')}</span></div><Badge tone={stateTone(w.state)}>{w.state}</Badge><button disabled title="Editing requires authenticated Merchant API session">Edit endpoint</button></div>)}</article><article className="panel"><div className="panel-head"><div><span className="eyebrow">DELIVERIES</span><h2>Recent attempts</h2></div></div><div className="table-wrap"><table><thead><tr><th>Event</th><th>Status</th><th>HTTP</th><th>Attempts</th><th>Timestamp</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td><code>{d.event}</code></td><td><Badge tone={stateTone(d.state)}>{d.state}</Badge></td><td>{d.httpStatus??'—'}</td><td>{d.attempts}</td><td>{d.timestamp}</td></tr>)}</tbody></table></div></article></section></div>}
function ApiLogs({env}:{env:Environment}){return <div className="page-stack"><PageHeader title="API logs" description="Safe operational request visibility without auth headers, secrets or customer-sensitive payloads."/><div className="contract-banner"><AlertTriangle size={16}/><div><strong>Backend dependency</strong><span>No merchant-facing request log collection exists in the inspected contract. The frontend will not fabricate request history.</span></div></div><article className="panel"><EmptyState title={`No ${env} API logs available`} detail="A merchant-scoped, sanitized API log endpoint is required before this surface can display real activity."/></article></div>}
function Team(){return <div className="page-stack"><PageHeader title="Team" description="Organization access model prepared for Owner, Admin, Developer, Finance, Operations and Viewer roles." action={<button className="primary-action" disabled title="Team management backend not available"><Users size={16}/>Invite member</button>}/><DataNotice/><article className="panel"><div className="team-list">{fallbackTeam.map(m=><div className="team-row" key={m.id}><span className="avatar small">{m.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><strong>{m.name}</strong><span>{m.email}</span></div><Badge>{m.role}</Badge><Badge tone={stateTone(m.status)}>{m.status}</Badge><small>{m.lastActive??'—'}</small><button disabled title="Role management requires backend permissions">•••</button></div>)}</div></article></div>}
function Account({env}:{env:Environment}){return <div className="page-stack"><PageHeader title="Account" description="Organization identity, merchant lifecycle and environment context."/><section className="detail-grid"><article className="panel account-card"><span className="eyebrow">ORGANIZATION</span><h2>{fallbackMerchant.name}</h2><dl><div><dt>Merchant ID</dt><dd><code>{fallbackMerchant.id}</code></dd></div><div><dt>Lifecycle</dt><dd><Badge tone={stateTone(fallbackMerchant.lifecycle)}>{fallbackMerchant.lifecycle}</Badge></dd></div><div><dt>Environment</dt><dd>{env}</dd></div></dl></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">SECURITY</span><h2>Access posture</h2></div></div><div className="security-list"><div><ShieldCheck size={17}/><span>Merchant API credentials stay server-side.</span></div><div><ShieldCheck size={17}/><span>Payment truth cannot be changed from the dashboard.</span></div><div><AlertTriangle size={17}/><span>Human account/session backend is still required for production dashboard authentication.</span></div></div></article></section></div>}
function SettingsPage(){return <div className="page-stack"><PageHeader title="Settings" description="Merchant preferences grouped without inventing unsupported financial controls."/><section className="settings-grid">{[['Business profile','Organization identity and customer-facing merchant information.'],['Checkout','Hosted Checkout presentation and redirect preferences.'],['Notifications','Operational notification preferences when backend support exists.'],['Integration','Environment and technical defaults.'],['Security','Human access, sessions and MFA when authentication contracts exist.']].map(([a,b])=><article className="setting-card" key={a}><SlidersHorizontal size={18}/><div><strong>{a}</strong><p>{b}</p></div><button disabled title="Settings mutation contract not available"><ChevronRight size={17}/></button></article>)}</section></div>}

function AppShell(){const[open,setOpen]=React.useState(false);const[env,setEnv]=React.useState<Environment>(()=>(localStorage.getItem('verox-env') as Environment)||'TEST');const change=(v:Environment)=>{setEnv(v);localStorage.setItem('verox-env',v)};return <div className="app-shell"><Sidebar open={open} onClose={()=>setOpen(false)}/><div className="workspace"><Topbar env={env} onEnv={change} onMenu={()=>setOpen(true)}/><main className="content"><Routes><Route path="/app/overview" element={<Overview env={env}/>}/><Route path="/app/payments" element={<PaymentsPage env={env}/>}/><Route path="/app/payments/:id" element={<PaymentDetail/>}/><Route path="/app/checkouts" element={<Checkouts env={env}/>}/><Route path="/app/reviews" element={<Reviews env={env}/>}/><Route path="/app/payment-channels" element={<PaymentChannels env={env}/>}/><Route path="/app/developers" element={<Integration env={env}/>}/><Route path="/app/api-keys" element={<ApiKeys env={env}/>}/><Route path="/app/webhooks" element={<WebhooksPage env={env}/>}/><Route path="/app/api-logs" element={<ApiLogs env={env}/>}/><Route path="/app/team" element={<Team/>}/><Route path="/app/account" element={<Account env={env}/>}/><Route path="/app/settings" element={<SettingsPage/>}/><Route path="/app" element={<Navigate to="/app/overview" replace/>}/><Route path="*" element={<Navigate to="/app/overview" replace/>}/></Routes></main></div>{open&&<button className="scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}</div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><AppShell/></BrowserRouter></React.StrictMode>);
