import React, {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,Check,CheckCircle2,ChevronRight,CircleAlert,Clock3,Copy,TriangleAlert,WifiOff} from 'lucide-react';
import './checkout-v2.css';
import './checkout-v2-tune.css';
import './polish.css';
import {checkoutApi,CheckoutApiError,readCheckoutContext} from './checkout-api';
import type {HostedCheckout,HostedPaymentChannel} from './checkout-api';

type Screen='loading'|'ready'|'instructions'|'evidence'|'submitted'|'verifying'|'confirmed'|'manual'|'review'|'failed'|'expired'|'network'|'invalid';
type ProviderView=HostedPaymentChannel&{logo:string;monogram:string};

function Brand({quiet=false}:{quiet?:boolean}){return <div className={`v2-brand ${quiet?'quiet':''}`} aria-label="VEROX"><img src="/verox-mark.svg" alt="" aria-hidden="true"/><div className="v2-wordmark"><strong>VEROX</strong>{!quiet&&<span>SECURE CHECKOUT</span>}</div></div>}
function AppChrome({children,screen}:{children:React.ReactNode;screen:Screen}){const stage=useMemo(()=>screen==='ready'||screen==='instructions'?1:screen==='evidence'?2:3,[screen]);return <main className="v2-page"><div className="v2-atmosphere" aria-hidden="true"><i/><i/><i/><i/></div><section className="v2-shell"><header className="v2-header"><Brand/><span className="v2-secure">Checkout seguro</span></header><div className="v2-steps" aria-label={`Etapa ${stage} de 3`}>{['Pagamento','Comprovativo','Verificação'].map((label,index)=>{const n=index+1;return <div className={`v2-step ${stage===n?'current':''} ${stage>n?'complete':''}`} key={label}><span>{stage>n?<Check size={12}/>:n}</span><b>{label}</b></div>})}</div><div className="v2-content">{children}</div><footer className="v2-footer product-footer"><div><span>Protegido por VEROX</span><small>A RIGHTWARE product</small></div></footer></section></main>}

function providerView(channel:HostedPaymentChannel):ProviderView{const key=channel.provider.toUpperCase();if(key.includes('MPESA')||key.includes('M_PESA'))return{...channel,logo:'/providers/m-pesa.png.png',monogram:'M'};if(key.includes('EMOLA')||key.includes('E_MOLA'))return{...channel,logo:'/providers/e-mola.png.png',monogram:'e'};if(key.includes('MILLENNIUM'))return{...channel,logo:'/providers/millennium-bim.png.png',monogram:'bim'};return{...channel,logo:'',monogram:channel.displayName.slice(0,2)}}
function ProviderMark({provider}:{provider:ProviderView}){const[failed,setFailed]=useState(!provider.logo);return <span className="v2-provider-mark">{failed?provider.monogram:<img src={provider.logo} alt="" aria-hidden="true" onError={()=>setFailed(true)}/>}</span>}
function money(checkout:HostedCheckout){return `${checkout.amount} ${checkout.currency}`}

function TransactionHero({checkout}:{checkout:HostedCheckout}){return <section className="v2-hero"><div className="v2-hero-meta"><span>Pagamento</span><strong>{checkout.externalReference}</strong></div><h1>{checkout.merchantDisplayName}</h1><div className="v2-money"><strong>{checkout.amount}</strong><span>{checkout.currency}</span></div>{checkout.description&&<p>{checkout.description}</p>}</section>}
function ProviderCard({provider,active,onSelect}:{provider:ProviderView;active:boolean;onSelect:()=>void}){return <button className={`v2-provider ${active?'active':''} ${!provider.enabled?'disabled':''}`} onClick={onSelect} disabled={!provider.enabled} aria-pressed={active} aria-label={`${provider.displayName}, ${provider.enabled?'Disponível':'Indisponível'}`}><ProviderMark provider={provider}/><span className="v2-provider-copy"><strong>{provider.displayName}</strong></span><span className={`v2-provider-status ${provider.enabled?'available':'soon'}`}>{provider.enabled?'Disponível':'Indisponível'}</span>{provider.enabled&&<ChevronRight size={18}/>}</button>}
function StickyAction({children,disabled,onClick}:{children:React.ReactNode;disabled?:boolean;onClick:()=>void}){return <div className="v2-action-dock"><button className="v2-primary" disabled={disabled} onClick={onClick}>{children}<ChevronRight size={18}/></button></div>}
function Back({onClick,children}:{onClick:()=>void;children:React.ReactNode}){return <button className="v2-back" onClick={onClick}><ArrowLeft size={16}/>{children}</button>}

function Ready({checkout,providers,selected,onSelect,onContinue}:{checkout:HostedCheckout;providers:ProviderView[];selected:string;onSelect:(id:string)=>void;onContinue:()=>void}){return <><TransactionHero checkout={checkout}/><section className="v2-section"><div className="v2-section-heading"><div><span className="v2-kicker">Método de pagamento</span><h2>Como pretende pagar?</h2></div><span className="v2-mini-trust">Opções disponíveis</span></div><div className="v2-provider-list">{providers.map(provider=><ProviderCard key={provider.provider} provider={provider} active={selected===provider.provider} onSelect={()=>onSelect(provider.provider)}/>)}</div><div className="v2-note"><p>Escolha um dos métodos disponíveis para este pagamento.</p></div></section><StickyAction disabled={!selected} onClick={onContinue}>Continuar</StickyAction></>}

function PaymentInstructions({checkout,provider,onBack,onPaid}:{checkout:HostedCheckout;provider:ProviderView;onBack:()=>void;onPaid:()=>void}){const[copied,setCopied]=useState(false);const copy=async()=>{if(!provider.recipientDisplay)return;try{await navigator.clipboard.writeText(provider.recipientDisplay);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setCopied(false)}};return <><Back onClick={onBack}>Voltar</Back><div className="v2-page-heading"><span className="v2-kicker">{provider.displayName}</span><h1>Faça o pagamento</h1><p>Use os dados abaixo exatamente como apresentados. Depois, volte aqui com a mensagem de confirmação recebida.</p></div><section className="v2-pay-card"><div className="v2-pay-card-brand"><ProviderMark provider={provider}/><div><strong>{provider.displayName}</strong></div></div><div className="v2-pay-card-top"><span>Valor a enviar</span><strong>{money(checkout)}</strong></div>{provider.recipientDisplay&&<div className="v2-recipient"><div><span>Enviar para</span><strong>{provider.recipientDisplay}</strong>{provider.recipientName&&<small>{provider.recipientName}</small>}</div><button onClick={copy} aria-label="Copiar dados de receção"><Copy size={17}/><span>{copied?'Copiado':'Copiar'}</span></button></div>}<div className="v2-pay-card-ref"><span>Referência</span><strong>{checkout.externalReference}</strong></div></section>{provider.instructions&&<section className="v2-howto"><h2>Como pagar</h2><div className="v2-howto-row"><span>01</span><div><strong>Siga as instruções do método</strong><p>{provider.instructions}</p></div></div><div className="v2-howto-row"><span>02</span><div><strong>Aguarde a mensagem de confirmação</strong><p>Guarde a mensagem oficial completa recebida após o pagamento.</p></div></div><div className="v2-howto-row"><span>03</span><div><strong>Volte ao VEROX</strong><p>No próximo passo, cole a mensagem completa para continuar.</p></div></div></section>}<div className="v2-critical"><p><strong>Importante:</strong> não edite nem reconstrua a mensagem de confirmação.</p></div><StickyAction onClick={onPaid}>Já efetuei o pagamento</StickyAction></>}

function Evidence({onBack,onSubmit,busy,error}:{onBack:()=>void;onSubmit:(value:string)=>void;busy:boolean;error:string|null}){const[value,setValue]=useState('');const max=4096;return <><Back onClick={onBack}>Instruções de pagamento</Back><div className="v2-page-heading"><span className="v2-kicker">Comprovativo</span><h1>Envie a confirmação</h1><p>Cole abaixo a mensagem completa recebida depois de efetuar o pagamento.</p></div><div className="v2-evidence-guide"><div><strong>Envie a mensagem completa.</strong><p>Use exatamente o conteúdo recebido, sem editar ou reconstruir.</p></div></div><label className="v2-field"><span>Mensagem de confirmação</span><textarea value={value} maxLength={max} onChange={e=>setValue(e.target.value)} placeholder="Cole aqui a mensagem completa de confirmação." autoComplete="off" spellCheck={false}/><div className="v2-field-meta"><small>Máximo de 4096 caracteres.</small><small>{value.length}/{max}</small></div></label>{error&&<div className="v2-state-callout warning"><span>{error}</span></div>}<div className="v2-privacy"><span>Os dados enviados são usados apenas para processar este pagamento.</span></div><StickyAction disabled={busy||!value.trim()} onClick={()=>onSubmit(value)}>{busy?'A enviar…':'Enviar confirmação'}</StickyAction></>}

function VerificationLoader(){return <div className="v2-verification-loader" role="status" aria-label="Verificação em curso"><svg viewBox="0 0 160 120" aria-hidden="true"><path className="vl-frame" d="M33 25h58v70H33z"/><path className="vl-core" d="M61 43l20 12v24L61 91 41 79V55z"/><circle className="vl-node n1" cx="119" cy="30" r="4"/><circle className="vl-node n2" cx="132" cy="57" r="4"/><circle className="vl-node n3" cx="116" cy="89" r="4"/><path className="vl-line l1" d="M91 42l24-10"/><path className="vl-line l2" d="M91 60l36-2"/><path className="vl-line l3" d="M91 79l22 9"/></svg></div>}
function StateScreen({checkout,provider,tone,icon,title,headline,body,children,action,onAction}:{checkout:HostedCheckout;provider?:ProviderView;tone:string;icon?:React.ReactNode;title:string;headline:string;body:string;children?:React.ReactNode;action?:string;onAction?:()=>void}){return <div className={`v2-state ${tone}`}>{icon&&<div className="v2-state-icon">{icon}</div>}<span className="v2-kicker">{title}</span><h1>{headline}</h1><div className="v2-state-amount">{money(checkout)}</div><p className="v2-state-body">{body}</p><div className="v2-state-meta"><div><span>Comerciante</span><strong>{checkout.merchantDisplayName}</strong></div><div><span>Método</span><strong>{provider?.displayName??'—'}</strong></div><div><span>Referência</span><strong>{checkout.externalReference}</strong></div></div>{children}{action&&<StickyAction onClick={onAction||(()=>{})}>{action}</StickyAction>}</div>}
function BasicState({tone='neutral',icon,title,headline,body,action,onAction}:{tone?:string;icon:React.ReactNode;title:string;headline:string;body:string;action?:string;onAction?:()=>void}){return <div className={`v2-state ${tone}`}><div className="v2-state-icon">{icon}</div><span className="v2-kicker">{title}</span><h1>{headline}</h1><p className="v2-state-body">{body}</p>{action&&<StickyAction onClick={onAction||(()=>{})}>{action}</StickyAction>}</div>}

function Submitted({checkout,provider}:{checkout:HostedCheckout;provider?:ProviderView}){return <StateScreen checkout={checkout} provider={provider} tone="info" icon={<CheckCircle2/>} title="Confirmação enviada" headline="Recebemos os dados do seu pagamento" body="O comerciante irá verificar o recebimento. Pode voltar ao site enquanto a confirmação é processada." action={checkout.successUrl?'Voltar ao comerciante':undefined} onAction={()=>checkout.successUrl&&window.location.assign(checkout.successUrl)}/>}

function statusScreen(checkout:HostedCheckout):Screen{if(checkout.checkoutStatus==='EXPIRED'||checkout.effectivePaymentStatus==='EXPIRED')return'expired';if(checkout.effectivePaymentStatus==='CONFIRMED')return'confirmed';if(checkout.evidenceSubmitted)return'submitted';if(checkout.effectivePaymentStatus==='MANUALLY_ACCEPTED')return'manual';if(checkout.effectivePaymentStatus==='REVIEW_REQUIRED')return'review';if(checkout.effectivePaymentStatus==='FAILED')return'failed';if(checkout.effectivePaymentStatus==='VERIFYING')return'verifying';return'ready'}

function App(){const[{checkoutSessionId,capability}]=useState(readCheckoutContext);const[checkout,setCheckout]=useState<HostedCheckout|null>(null);const[screen,setScreen]=useState<Screen>('loading');const[selected,setSelected]=useState('');const[evidenceBusy,setEvidenceBusy]=useState(false);const[evidenceError,setEvidenceError]=useState<string|null>(null);const[networkError,setNetworkError]=useState(false);
const bootstrap=React.useCallback(async(showNetwork=true)=>{if(!checkoutSessionId||!capability){setScreen('invalid');return null}try{const data=await checkoutApi.bootstrap(checkoutSessionId,capability);setCheckout(data);setNetworkError(false);const enabled=data.paymentChannels.filter(channel=>channel.enabled);setSelected(current=>current&&enabled.some(channel=>channel.provider===current)?current:(enabled[0]?.provider||''));const authoritative=statusScreen(data);if(['confirmed','manual','review','failed','expired','verifying','submitted'].includes(authoritative))setScreen(authoritative);else if(screen==='loading'||screen==='network'||screen==='invalid')setScreen('ready');return data}catch(error){if(error instanceof CheckoutApiError&&error.status===0){setNetworkError(true);if(showNetwork)setScreen('network')}else setScreen('invalid');return null}},[checkoutSessionId,capability,screen]);
useEffect(()=>{bootstrap()},[]);
useEffect(()=>{if(screen!=='verifying')return;const timer=window.setInterval(()=>bootstrap(false),2500);return()=>window.clearInterval(timer)},[screen,bootstrap]);
const providers=useMemo(()=>checkout?.paymentChannels.filter(channel=>channel.enabled).map(providerView)??[],[checkout]);const provider=providers.find(item=>item.provider===selected);
async function submitEvidence(value:string){if(!checkout||!capability||!selected)return;setEvidenceBusy(true);setEvidenceError(null);try{await checkoutApi.submitEvidence(checkout.checkoutSessionId,capability,selected,value.trim());setScreen('verifying');await bootstrap(false)}catch(error){if(error instanceof CheckoutApiError&&error.status===0){setNetworkError(true);setScreen('network')}else setEvidenceError(error instanceof Error?error.message:'Não foi possível enviar a confirmação.')}finally{setEvidenceBusy(false)}}
if(screen==='loading')return <AppChrome screen="verifying"><BasicState icon={<VerificationLoader/>} title="Checkout VEROX" headline="A preparar o pagamento" body="Um momento enquanto carregamos os dados do checkout."/></AppChrome>;
if(screen==='invalid')return <AppChrome screen="invalid"><BasicState icon={<CircleAlert/>} title="Checkout indisponível" headline="Este link não está disponível" body="O link pode estar incorreto, ter expirado ou já não estar disponível."/></AppChrome>;
if(screen==='network'||!checkout)return <AppChrome screen="network"><BasicState icon={<WifiOff/>} title="Ligação indisponível" headline="Não foi possível carregar o checkout" body="Verifique a sua ligação e tente novamente. O estado do pagamento não foi alterado." action="Tentar novamente" onAction={()=>bootstrap()}/></AppChrome>;
let content:React.ReactNode;
switch(screen){case'ready':content=<Ready checkout={checkout} providers={providers} selected={selected} onSelect={setSelected} onContinue={()=>provider&&setScreen('instructions')}/>;break;case'instructions':content=provider?<PaymentInstructions checkout={checkout} provider={provider} onBack={()=>setScreen('ready')} onPaid={()=>setScreen('evidence')}/>:<BasicState icon={<CircleAlert/>} title="Método indisponível" headline="Nenhum método está disponível" body="Não existem métodos de pagamento disponíveis para este checkout neste momento."/>;break;case'evidence':content=<Evidence onBack={()=>setScreen('instructions')} onSubmit={submitEvidence} busy={evidenceBusy} error={evidenceError}/>;break;case'submitted':content=<Submitted checkout={checkout} provider={provider}/>;break;
case'verifying':content=<StateScreen checkout={checkout} provider={provider} tone="info" icon={<VerificationLoader/>} title="Em verificação" headline="Estamos a verificar o seu pagamento" body="Recebemos a sua confirmação e estamos a processá-la."><div className="v2-state-callout info"><span>Não precisa de enviar a mensagem novamente.</span></div></StateScreen>;break;case'confirmed':content=<StateScreen checkout={checkout} provider={provider} tone="success" icon={<CheckCircle2/>} title="Pagamento confirmado" headline="O pagamento foi confirmado" body="A confirmação deste pagamento foi concluída." action="Voltar ao comerciante" onAction={()=>window.location.assign(checkout.successUrl)}/>;break;case'manual':content=<StateScreen checkout={checkout} provider={provider} tone="success" icon={<CheckCircle2/>} title="Pagamento confirmado" headline="O pagamento foi confirmado" body="O comerciante confirmou o recebimento deste pagamento." action="Voltar ao comerciante" onAction={()=>window.location.assign(checkout.successUrl)}/>;break;case'review':content=<StateScreen checkout={checkout} provider={provider} tone="warning" icon={<TriangleAlert/>} title="Requer atenção" headline="A confirmação está a ser analisada" body="A informação foi recebida, mas o pagamento ainda não está confirmado."><div className="v2-state-callout warning"><strong>Não efetue outro pagamento.</strong><span>A transação pode já ter sido efetuada.</span></div></StateScreen>;break;case'failed':content=<StateScreen checkout={checkout} provider={provider} tone="danger" icon={<CircleAlert/>} title="Pagamento não concluído" headline="Não foi possível confirmar este pagamento" body="Este pagamento não foi concluído. Consulte o comerciante se precisar de ajuda." action="Voltar ao comerciante" onAction={()=>window.location.assign(checkout.cancelUrl)}/>;break;case'expired':content=<StateScreen checkout={checkout} provider={provider} tone="neutral" icon={<Clock3/>} title="Checkout expirado" headline="Este checkout já não está ativo" body="A sessão terminou e já não pode receber uma nova confirmação." action="Voltar ao comerciante" onAction={()=>window.location.assign(checkout.cancelUrl)}/>;break;default:content=null}
return <AppChrome screen={screen}>{content}{networkError&&<div className="v2-state-callout warning"><span>A ligação foi interrompida. Tente novamente para obter o estado mais recente.</span></div>}</AppChrome>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
